version: '3'
services:
    api-service:
        build: ./project-micro-app/
        ports: 
            - 5001:5001
    web:
        build: ./
        ports:
            - "5000:5000"
        links:
            - db
    db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=aditya
            - POSTGRES_PASSWORD=Supersecret
            - POSTGRES_DB=projectA
        ports:
            - "5432:5432"
    
volumes:
  postgres_data: