version: '3'
services:
    project-micro-app:
        build: ./project-micro-app/
        ports: 
            - 5001:5001
    email-report-micro-app:
        build: ./email-report-micro-app/
        ports: 
            - 5002:5002
    update-status-micro-app:
        build: ./update-status-micro-app/
        ports: 
            - 5050:5050
    web:
        build: ./
        ports:
            - 5000:5000
        links:
            - db
    db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=aditya
            - POSTGRES_PASSWORD=Supersecret
            - POSTGRES_DB=projectA
        ports:
            - "5432:5432"
    
volumes:
  postgres_data: