version: '3'
services:
    web:
        build: ./
        ports:
            - "5007:5007"
        links:
            - db
    db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=aditya
            - POSTGRES_PASSWORD=Supersecret
            - POSTGRES_DB=projectC
        ports:
            - "5432:5432"
    
volumes:
  postgres_data: